version: "3"

services:
  todoapp-backend:
    build: ./ToDoAppBackend
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_HEALTH_ENABLED=true
    command: start-dev
