spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI}/protocol/openid-connect/certs

# Configuration de sécurité additionnelle
auth:
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID:todoapp-api}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}
    realm: ${KEYCLOAK_REALM:master}

server:
  port: ${PORT:8080}
