spring:
  application:
    name: todo-app

  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://todoappkeycloak-production.up.railway.app/realms/todo-backend}

  web:
    cors:
      allowed-origins:
        - "https://todoappnhat.netlify.app"
      allowed-methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Configuration Swagger UI pour production
springdoc:
  swagger-ui:
    enabled: true
    oauth:
      client-id: todo-backend-client
      client-secret: 48X6oHEI8EFSaCVYVBYy3FtAWnYswMnE
      realm: todo-backend
      app-name: ToDo API
      scopes:
        - openid
        - profile
        - email
  api-docs:
    path: /v3/api-docs
    enabled: true

# Actuator health (optionnel)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: INFO
    com.example.ToDoApp: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
