spring:
  datasource:
    url: jdbc:postgresql://todo-db.cpgem82oyryx.eu-north-1.rds.amazonaws.com:5432/todo-db # ← ici la base était fausse
    username: postgres
    password: Postgres2025!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://13.60.230.231:8081/realms/ToDoApp

  profiles:
    active: prod
