spring:
  application:
    name: todo-app

  profiles:
    active: ${ACTIVE_PROFILE:dev}
---
# Bloc DEV (in-mem H2)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/todo-backend

  web:
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "http://localhost:8081"
        - "https://localhost:4200"
      allowed-methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Swagger UI en DEV
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth2-redirect-url: http://localhost:8081/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: todo-backend-client
      client-secret: ${KEYCLOAK_CLIENT_SECRET:}
      realm: todo-backend
      app-name: ToDo API
      scopes: ["openid", "profile", "email"]

# Keycloak local
auth:
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID:todo-backend-client}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}
    realm: ${KEYCLOAK_REALM:todo-backend}
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}

server:
  port: 8081
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

logging:
  level:
    com.example.ToDoApp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.springdoc: DEBUG
